@startuml UC61_AdminKhoaMoKhoaVi
title Admin khóa/mở khóa ví

autonumber "<b>[00]</b>"
skinparam sequenceArrowThickness 2
skinparam roundcorner 10
skinparam defaultFontSize 20
skinparam titleFontSize 26
skinparam sequenceFontSize 19
skinparam sequenceMessageFontSize 20
skinparam sequenceActorFontSize 20
skinparam sequenceParticipantFontSize 20
skinparam noteFontSize 18
skinparam sequenceArrowFontSize 20
skinparam sequence {
    ParticipantPadding 30
    LifeLinePadding 20
    MessagePadding 10
}

actor "Admin" as Admin
boundary ":AdminWalletUI" as UI
control ":WalletController" as CTRL
entity ":Wallet" as ENT
database ":CSDL" as DB

Admin -> UI : Nhấn Toggle khóa/mở khóa ví
activate UI

UI -> CTRL : toggleWalletStatus(walletId)
activate CTRL
CTRL -> ENT : PUT /api/admin/wallets/lock/{id} hoặc /unlock/{id}
activate ENT
ENT -> DB : Cập nhật trạng thái ví (ACTIVE <-> LOCKED)
activate DB
DB --> ENT : 200 OK
deactivate DB
ENT --> CTRL : Đã cập nhật
deactivate ENT
CTRL --> UI : Thành công
deactivate CTRL

UI --> Admin : Cập nhật UI trạng thái mới

deactivate UI
@enduml
